# Generated by Django 4.2 on 2024-01-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_employee',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
